twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello from twitter-to-kafka-service!

retry-config:
  initial-interval: 1000
  max-interval: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleepTime: 2000
